header:
  version : 14
  includes:
    - repo: meta-mender-kernel
      file: kas/kas.yml
    - repo: meta-mender-kernel
      file: kas/meta-secure-core.yml

repos:
  meta-mender-luks:

  meta-mender-kernel:
    url   : "https://github.com/coreycothrum/meta-mender-kernel.git"
    branch: master
    commit: 6059c50a8f6d694a372df35f6d1fdf61a0155922

  meta-secure-core:
    layers :
      meta-encrypted-storage:
