header:
  version : 14
  includes:
    - repo: meta-mender-kernel
      file: kas/kas.yml
    - repo: meta-mender-kernel
      file: kas/meta-secure-core.yml

repos:
  meta-mender-luks:

  meta-mender-kernel:
    url   : "https://github.com/coreycothrum/meta-mender-kernel.git"
    branch: master
    commit: 5a5f1589356463c30cc4211d56f364209984e376

  meta-secure-core:
    layers :
      meta-encrypted-storage:
