header:
  version : 14
  includes:
    - repo: meta-mender-kernel
      file: kas/kas.yml
    - repo: meta-mender-kernel
      file: kas/meta-secure-core.yml

repos:
  meta-mender-luks:

  meta-mender-kernel:
    url   : "https://github.com/coreycothrum/meta-mender-kernel.git"
    branch: master
    commit: a497f4092e47d296cde5ee1b7f2015942b23462f

  meta-secure-core:
    layers :
      meta-encrypted-storage:
