header:
  version : 14
  includes:
    - repo: meta-mender-kernel
      file: kas/kas.yml
    - repo: meta-mender-kernel
      file: kas/meta-secure-core.yml

repos:
  meta-mender-luks:

  meta-mender-kernel:
    url   : "https://github.com/coreycothrum/meta-mender-kernel.git"
    branch: wrynose
    commit: 6a79d5869cbc2b61a077f0a34b258556c4add218

  meta-secure-core:
    layers :
      meta-encrypted-storage:
